In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized version: " + str(1000*(toc-tic)) + "ms")

c=0
tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc = time.time()
print(c)
print("For loop:" + str(1000*(toc-tic))+ "ms")

250005.09203026778
Vectorized version: 37.38975524902344ms
250005.0920302641
For loop:661.229133605957ms


In [3]:
import pandas as pd

u = np.zeros((3,4))
u[0][0]=56.0
u[1][0]=1.2
u[2][0]=1.8
u[0][1]=0.0
u[1][1]=104.0
u[2][1]=135
u[0][2]=4.4
u[1][2]=52
u[2][2]=99
u[0][3]=68
u[1][3]=8
u[2][3]=0.9
sumcol = np.sum(u,axis=0)
ans = u/sumcol*100

print(ans)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [4]:
a = np.random.randn(5)
print(a)

[ 1.36982151 -0.70316803  0.94033206 -1.26065317 -0.15216134]


In [5]:
print (a.shape)

(5,)


In [6]:
a = np.random.randn(5,1)
a

array([[-0.5702441 ],
       [-1.32015945],
       [ 0.5443347 ],
       [ 0.77061273],
       [-1.2155094 ]])

In [7]:
print(a*a.T)

[[ 0.32517834  0.75281314 -0.31040365 -0.43943736  0.69313707]
 [ 0.75281314  1.74282098 -0.7186086  -1.01733168  1.60466622]
 [-0.31040365 -0.7186086   0.29630027  0.41947125 -0.66164395]
 [-0.43943736 -1.01733168  0.41947125  0.59384398 -0.93668701]
 [ 0.69313707  1.60466622 -0.66164395 -0.93668701  1.4774631 ]]


In [8]:
a = np.random.randn(2,3)
b = np.random.randn(2,1)
c=a*b
print (a)
print(b)
print(c)

[[ 0.81139032  1.19913932  0.08648986]
 [-0.44226555  1.04823134  1.21302021]]
[[-1.73503111]
 [ 1.21697006]]
[[-1.40778745 -2.08054401 -0.1500626 ]
 [-0.53822393  1.27566616  1.47620928]]


In [9]:
a.shape[1]

3

In [11]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
B

array([[0.27323935],
       [1.18134613],
       [4.56696935],
       [0.1644261 ]])