In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized version: " + str(1000*(toc-tic)) + "ms")

c=0
tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc = time.time()
print(c)
print("For loop:" + str(1000*(toc-tic))+ "ms")

250051.80588834913
Vectorized version: 1.9516944885253906ms
250051.80588834255
For loop:1222.728967666626ms


In [19]:
import pandas as pd

u = np.zeros((3,4))
u[0][0]=56.0
u[1][0]=1.2
u[2][0]=1.8
u[0][1]=0.0
u[1][1]=104.0
u[2][1]=135
u[0][2]=4.4
u[1][2]=52
u[2][2]=99
u[0][3]=68
u[1][3]=8
u[2][3]=0.9
sumcol = np.sum(u,axis=0)
ans = u/sumcol*100

print(ans)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [24]:
a = np.random.randn(5)
print(a)

[-1.83366328 -0.37316916  1.18186365  1.97059215  0.48108807]


In [22]:
print (a.shape)

(5,)


In [26]:
a = np.random.randn(5,1)
a

array([[-0.05258688],
       [-0.19191959],
       [-0.42508566],
       [-0.5194138 ],
       [ 0.5724532 ]])

In [27]:
print(a*a.T)

[[ 0.00276538  0.01009245  0.02235393  0.02731435 -0.03010353]
 [ 0.01009245  0.03683313  0.08158227  0.09968568 -0.10986498]
 [ 0.02235393  0.08158227  0.18069782  0.22079536 -0.24334164]
 [ 0.02731435  0.09968568  0.22079536  0.26979069 -0.29734009]
 [-0.03010353 -0.10986498 -0.24334164 -0.29734009  0.32770266]]
